sudo: required
services:
    - docker


before_install:
    - docker build -t 28ayushsharma/angular-docker -f Dockerfile.dev .

scripts:
    - docker run 28ayushsharma/angular-docker npm run test -- --no-watch --code-coverage
