FROM node:15.14.0-alpine3.10

RUN apk add chromium
WORKDIR '/app'
ENV CHROME_BIN=/usr/bin/chromium-browser

COPY package.json .
RUN npm install
RUN npm install -g @angular/cli

COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0"]